### ISSUE TITLE
JavaDoc giving 403 forbidden

### ISSUE THREAD

**Issue by stuartmarsden** [dstl/baleen#16] opened 2016-03-16 18:34 UTC
I have compiled successfully but cannot access the javadoc. I copied the file baleen-javadoc-2.2.0-SNAPSHOT.jar in to the same directory but it is not found and I get a 404. If I change the filename to baleen-2.2.0-SNAPSHOT-javadoc.jar then I can see from the log it finds the javadoc file. I then however get a 403 error when I try to go to it.

The is a bit frustrating as I need to read the javadoc to be able to figure out how to use baleen.

This is on the latest commit c862249 

Relevant Log when starting baleen

`2016-03-16 22:30:40,269 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.h.ContextHandler@77be656f{/javadoc,jar:file:/home/stuart/Programming/workrelated/baleen/baleen/target/baleen-2.2.0-SNAPSHOT-javadoc.jar!/,AVAILABLE}`

**Comment by NG-3** [comment] 2016-03-17 17:17
Hi Stuart,
I notice you are using linux, I too had trouble getting the javadoc to display.
Below is a set of verbose logs from the jetty server that handles the Javadoc display.
The workaround I used was to use the baleen-2.1.0 tag on dstl to view the javadoc.

```
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.io.ManagedSelector - Selector loop woken up from select, 1/1 selected
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.io.SelectChannelEndPoint - onSelected 1->0 r=true w=false for SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,R,-,1991/30000,HttpConnection}{io=1/0,kio=1,kro=1}
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.io.SelectChannelEndPoint - task SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,R,-,1991/30000,HttpConnection}{io=1/0,kio=1,kro=1}:runFillable
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume - EPR Prod/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298 produced SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,R,-,1991/30000,HttpConnection}{io=1/0,kio=1,kro=1}:runFillable
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume - EPR Pend/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298 dispatch
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.util.thread.QueuedThreadPool - queue EPR Pend/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.util.thread.QueuedThreadPool - run EPR Pend/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume - EPR Pend/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298 run SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,R,-,1991/30000,HttpConnection}{io=1/0,kio=1,kro=1}:runFillable
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume - EPR Pend/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298 run
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume - EPR Prod/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298 produce enter
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume - EPR Prod/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298 producing
2016-03-17 17:06:06,096 DEBUG org.eclipse.jetty.io.FillInterest - FillInterest@71f23258{true,AC.ReadCB@eb8f3ed{HttpConnection@eb8f3ed<--null}} fillable AC.ReadCB@eb8f3ed{HttpConnection@eb8f3ed<--null}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpConnection - HttpConnection@eb8f3ed<--null onFillable enter HttpChannelState@20867e1c{s=IDLE a=null i=true r=!P!U w=false}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.io.SelectChannelEndPoint - Key interests updated 1 -> 0 on SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,-,-,1992/30000,HttpConnection}{io=0/0,kio=0,kro=1}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.io.ManagedSelector - Selector loop waiting on select
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.io.ChannelEndPoint - filled 292 SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,-,-,1992/30000,HttpConnection}{io=0/0,kio=0,kro=1}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpConnection - HttpConnection@eb8f3ed<--HeapByteBuffer@7ca2ef7f[p=0,l=292,c=8192,r=292]={<<<GET /javadoc/ HTT... keep-alive\r\n\r\n>>>ive\r\n\r\n\n\r\nection:...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} filled 292
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpConnection - HttpConnection@eb8f3ed<--HeapByteBuffer@7ca2ef7f[p=0,l=292,c=8192,r=292]={<<<GET /javadoc/ HTT... keep-alive\r\n\r\n>>>ive\r\n\r\n\n\r\nection:...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} parse HeapByteBuffer@7ca2ef7f[p=0,l=292,c=8192,r=292]={<<<GET /javadoc/ HTT... keep-alive\r\n\r\n>>>ive\r\n\r\n\n\r\nection:...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} {}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - parseNext s=START HeapByteBuffer@7ca2ef7f[p=0,l=292,c=8192,r=292]={<<<GET /javadoc/ HTT... keep-alive\r\n\r\n>>>ive\r\n\r\n\n\r\nection:...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - START --> SPACE1
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - SPACE1 --> URI
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - URI --> SPACE2
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - SPACE2 --> REQUEST_VERSION
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - REQUEST_VERSION --> HEADER
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER --> HEADER_IN_VALUE
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER_IN_VALUE --> HEADER
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER --> HEADER_IN_VALUE
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER_IN_VALUE --> HEADER
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER --> HEADER_IN_VALUE
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER_IN_VALUE --> HEADER
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER --> HEADER_IN_VALUE
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER_IN_VALUE --> HEADER
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER --> HEADER_IN_VALUE
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER_IN_VALUE --> HEADER
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER --> HEADER_IN_VALUE
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER_IN_VALUE --> HEADER
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.http.HttpParser - HEADER --> END
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpChannel - HttpChannelOverHttp@76091e56{r=7,c=false,a=IDLE,uri=-} onRequestComplete
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpInput - org.eclipse.jetty.server.HttpInputOverHTTP@1541b276 addContent EOF
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpConnection - HttpConnection@eb8f3ed<--HeapByteBuffer@7ca2ef7f[p=292,l=292,c=8192,r=0]={GET /javadoc/ HTT... keep-alive\r\n\r\n<<<>>>ive\r\n\r\n\n\r\nection:...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} parsed true HttpParser{s=END,0 of -1}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpConnection - releaseRequestBuffer HttpConnection@eb8f3ed<--HeapByteBuffer@7ca2ef7f[p=292,l=292,c=8192,r=0]={GET /javadoc/ HTT... keep-alive\r\n\r\n<<<>>>ive\r\n\r\n\n\r\nection:...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpChannel - HttpChannelOverHttp@76091e56{r=7,c=false,a=IDLE,uri=-} handle //localhost:6413/javadoc/ 
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpChannelState - HttpChannelState@20867e1c{s=IDLE a=null i=true r=!P!U w=false} handling IDLE
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpChannel - HttpChannelOverHttp@76091e56{r=7,c=false,a=DISPATCHED,uri=/javadoc/} action REQUEST_DISPATCH
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.Server - REQUEST on HttpChannelOverHttp@76091e56{r=7,c=false,a=DISPATCHED,uri=/javadoc/}
GET //localhost:6413/javadoc/
Host: localhost:6413
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive


2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.handler.ContextHandler - scope null||/javadoc/ @ o.e.j.s.ServletContextHandler@66b59b7d{/api/1,null,AVAILABLE}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.handler.ContextHandler - scope null||/javadoc/ @ o.e.j.s.h.ContextHandler@5d8ab698{/javadoc,jar:file:/home/thellier/workspace/Baleen-shared-with-James-Baker/deployment/bin/baleen-2.2.0-SNAPSHOT-javadoc.jar!/,AVAILABLE}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.handler.ContextHandler - context=/javadoc||/ @ o.e.j.s.h.ContextHandler@5d8ab698{/javadoc,jar:file:/home/thellier/workspace/Baleen-shared-with-James-Baker/deployment/bin/baleen-2.2.0-SNAPSHOT-javadoc.jar!/,AVAILABLE}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.handler.ResourceHandler - o.e.j.s.h.ContextHandler@5d8ab698{/javadoc,jar:file:/home/thellier/workspace/Baleen-shared-with-James-Baker/deployment/bin/baleen-2.2.0-SNAPSHOT-javadoc.jar!/,AVAILABLE} getResource(null)
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.handler.ResourceHandler - resource=jar:file:/home/thellier/workspace/Baleen-shared-with-James-Baker/deployment/bin/baleen-2.2.0-SNAPSHOT-javadoc.jar!/ alias=null exists=true
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpChannel - Commit HTTP/1.1{s=403,h=4} to HttpChannelOverHttp@76091e56{r=7,c=true,a=DISPATCHED,uri=/javadoc/}
2016-03-17 17:06:06,097 DEBUG org.eclipse.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@6dcc501[PROCESSING][i=HTTP/1.1{s=403,h=4},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@4cacd86a] generate: NEED_HEADER (null,[p=0,l=323,c=2048,r=323],true)@START
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@6dcc501[PROCESSING][i=HTTP/1.1{s=403,h=4},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@4cacd86a] generate: FLUSH ([p=0,l=209,c=8192,r=209],[p=0,l=323,c=2048,r=323],true)@COMPLETING
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.WriteFlusher - write: WriteFlusher@53a0b6aa{IDLE} [HeapByteBuffer@2ec67e05[p=0,l=209,c=8192,r=209]={<<<HTTP/1.1 403 Forb...z-SNAPSHOT)\r\n\r\n>>>anguage: en-GB,en...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00},HeapByteBuffer@3727a929[p=0,l=323,c=2048,r=323]={<<<<html>\n<head>\n<me.../body>\n</html>\n>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}]
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@53a0b6aa{WRITING}:IDLE-->WRITING
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.ChannelEndPoint - flushed 532 SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,-,W,1/30000,HttpConnection}{io=0/0,kio=0,kro=1}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.WriteFlusher - Flushed=true 209/209+1 WriteFlusher@53a0b6aa{WRITING}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@53a0b6aa{IDLE}:WRITING-->IDLE
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@6dcc501[PROCESSING][i=HTTP/1.1{s=403,h=4},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@4cacd86a] generate: DONE ([p=209,l=209,c=8192,r=0],[p=323,l=323,c=2048,r=0],true)@END
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.Server - RESPONSE for /javadoc/ h=true
403 null
Date: Thu, 17 Mar 2016 17:06:06 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 323


2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.HttpChannelState - HttpChannelState@20867e1c{s=DISPATCHED a=null i=true r=!P!U w=false} unhandle DISPATCHED
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.http.HttpParser - reset HttpParser{s=END,0 of -1}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.http.HttpParser - END --> START
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.HttpChannel - HttpChannelOverHttp@76091e56{r=7,c=false,a=IDLE,uri=-} handle exit, result COMPLETE
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.ChannelEndPoint - filled 0 SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,-,-,0/30000,HttpConnection}{io=0/0,kio=0,kro=1}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.ChannelEndPoint - filled 0 SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,-,-,0/30000,HttpConnection}{io=0/0,kio=0,kro=1}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.HttpConnection - HttpConnection@eb8f3ed<--HeapByteBuffer@7ca2ef7f[p=0,l=0,c=8192,r=0]={<<<>>>GET /javadoc/ HTT...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} filled 0
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.HttpConnection - HttpConnection@eb8f3ed<--HeapByteBuffer@7ca2ef7f[p=0,l=0,c=8192,r=0]={<<<>>>GET /javadoc/ HTT...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} parse HeapByteBuffer@7ca2ef7f[p=0,l=0,c=8192,r=0]={<<<>>>GET /javadoc/ HTT...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} {}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.http.HttpParser - parseNext s=START HeapByteBuffer@7ca2ef7f[p=0,l=0,c=8192,r=0]={<<<>>>GET /javadoc/ HTT...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.HttpConnection - HttpConnection@eb8f3ed<--HeapByteBuffer@7ca2ef7f[p=0,l=0,c=8192,r=0]={<<<>>>GET /javadoc/ HTT...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} parsed false HttpParser{s=START,0 of -1}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.HttpConnection - releaseRequestBuffer HttpConnection@eb8f3ed<--HeapByteBuffer@7ca2ef7f[p=0,l=0,c=8192,r=0]={<<<>>>GET /javadoc/ HTT...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.AbstractConnection - fillInterested HttpConnection@eb8f3ed<--null
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.FillInterest - FillInterest@71f23258{true,AC.ReadCB@eb8f3ed{HttpConnection@eb8f3ed<--null}} register AC.ReadCB@eb8f3ed{HttpConnection@eb8f3ed<--null}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.FillInterest - FillInterest@71f23258{true,AC.ReadCB@eb8f3ed{HttpConnection@eb8f3ed<--null}} register AC.ReadCB@eb8f3ed{HttpConnection@eb8f3ed<--null}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.SelectChannelEndPoint - changeInterests p=false 0->1 for SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,R,-,0/30000,HttpConnection}{io=0/1,kio=0,kro=1}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.ManagedSelector - Queued change SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,R,-,0/30000,HttpConnection}{io=0/1,kio=0,kro=1}:runUpdateKey on org.eclipse.jetty.io.ManagedSelector@376c7d7d id=3 keys=1 selected=0
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.server.HttpConnection - HttpConnection@eb8f3ed<--null onFillable exit HttpChannelState@20867e1c{s=IDLE a=null i=true r=!P!U w=false}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.ManagedSelector - Selector loop woken up from select, 0/1 selected
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume - EPR Prod/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298 ran SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,R,-,0/30000,HttpConnection}{io=0/1,kio=0,kro=1}:runFillable
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.ManagedSelector - Running change SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,R,-,0/30000,HttpConnection}{io=0/1,kio=0,kro=1}:runUpdateKey
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume - EPR Prod/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298 produce exit
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.util.thread.QueuedThreadPool - ran EPR Prod/org.eclipse.jetty.io.ManagedSelector$SelectorProducer@5e272298
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.SelectChannelEndPoint - Key interests updated 0 -> 1 on SelectChannelEndPoint@11ddcd17{/127.0.0.1:52596<->6413,Open,in,out,R,-,0/30000,HttpConnection}{io=1/1,kio=1,kro=1}
2016-03-17 17:06:06,098 DEBUG org.eclipse.jetty.io.ManagedSelector - Selector loop waiting on select
```

**Comment by NG-1** [comment] 2016-03-18 09:35
Hi Tom are there any Linux dev notes that we can add to the Wiki?

**Comment by stuartmarsden** [comment] 2016-03-18 09:41
Hi thanks for quick response. You mean if I build the 2.1.0 tag that it works and that I can then copy the javadoc and use with later builds? I am traveling at the moment so cannot just try it.

**Comment by jbaker-dstl** [comment] 2016-03-21 08:52
Thanks for flagging this @stuartmarsden, I hadn't hit this issue before so I'll have a look into it when I get a chance. Are you using any of the web configuration settings in your config.yaml file?

As a workaround, if you don't need some of the new features from the latest snapshot builds, you could use the pre-built release version: https://github.com/dstl/baleen/releases

**Comment by stuartmarsden** [comment] 2016-03-22 12:17
Travelling so cannot try on my original set up but have downloaded 2.1.0 on to my Windows 10 laptop. Had to move it out of my user directory to avoid the spaces in the path bug but now works at least.

I will confirm on my Linux box when I get back whether 2.1.0 works okay.

Have not made a config.yaml yet as I am still trying to figure out how to use Baleen. Not even sure if it is the right tool for the job yet. I am looking at how we might automatically get some structured data out of documents in a repository (ie Sharepoint) or text in Mediawiki. 

Quite new to this particular area so will be a steep learning curve by the look of it. I am a big open source fan and would like to support DSTL and utilise the tool if possible.

Is there a simple start setup that for instance scans documents in a directory and then outputs some sort of human readable file?

**Comment by jbaker-dstl** [comment] 2016-03-22 12:53
@stuartmarsden Have a look at the Sample Pipeline on the wiki: https://github.com/dstl/baleen/wiki/Sample-Pipeline

That will output into Mongo and Elasticsearch, though if you don't have either of those you could use the Html5 consumer instead.

**Comment by jbaker-dstl** [comment] 2016-03-23 08:46
I've tried the latest snapshot on a CentOS server, and didn't have any issues getting the JavaDoc to work. I was able to reproduce a 403 error by changing the permissions on the JavaDoc JAR so that Java didn't have read access - could that be your problem?

**Comment by jbaker-dstl** [comment] 2016-04-12 13:54
@stuartmarsden, did you find out whether this was caused by a permissions error on your file system? I've been unable to replicate the problem, so without further information I will close this bug.

**Comment by stuartmarsden** [comment] 2016-04-12 15:16
Sorry took a while to look in to this I have been travelling. It is not a permissions issue it seems to be a build issue. If I take the 2.1.0 release javadoc and rename to match with the same permissions it works fine.

I do note that the file size is totally different so I do not think my build has actually made the javadoc.

```
-rw-r--r-- 1 stuart stuart 108268797 Mar 16 21:59 baleen-2.2.0-SNAPSHOT.jar
-rw-r--r-- 1 stuart stuart   2004712 Mar 27 22:01 baleen-2.2.0-SNAPSHOT-javadoc.jar
-rw-r--r-- 1 stuart stuart      8400 Mar 16 21:59 baleen-2.2.0-SNAPSHOT-javadoc.jar.bak
```
You can see above that the permissions are all the same. In this case baleen-2.2.0-SNAPSHOT-javadoc.jar is actually the 2.1.0 javadoc I have renamed and you can see is around 2MB. baleen-2.2.0-SNAPSHOT-javadoc.jar.bak is the actual one that built and you can see it is only 8400B so probably does not actually contain anything.

I have just switched to using the release version for now but can try a build again of you need anything to help diagnose.

**Comment by stuartmarsden** [comment] 2016-04-12 15:40
If it helps this is the build log from the javadoc part to the end.

```
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Baleen Javadoc 2.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.4.201502262128:prepare-agent (default-prepare-agent) @ baleen-javadoc ---
[INFO] argLine set to -javaagent:/home/stuart/.m2/repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=/home/stuart/Programming/workrelated/baleen/baleen/baleen-javadoc/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ baleen-javadoc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ baleen-javadoc ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ baleen-javadoc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ baleen-javadoc ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ baleen-javadoc ---
[INFO] Surefire report directory: /home/stuart/Programming/workrelated/baleen/baleen/baleen-javadoc/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running uk.gov.dstl.baleen.javadoc.BaleenJavadocTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.093 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.4.201502262128:report (default-report) @ baleen-javadoc ---
[INFO] Analyzed bundle 'Baleen Javadoc' with 4 classes
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ baleen-javadoc ---
[INFO] Building jar: /home/stuart/Programming/workrelated/baleen/baleen/baleen-javadoc/target/baleen-javadoc-2.2.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Baleen ............................................. SUCCESS [  0.588 s]
[INFO] Baleen Core ........................................ SUCCESS [ 17.464 s]
[INFO] Baleen UIMA ........................................ SUCCESS [  4.784 s]
[INFO] Baleen Resources ................................... SUCCESS [ 35.032 s]
[INFO] Baleen Annotators .................................. SUCCESS [ 32.188 s]
[INFO] Baleen Collection Readers .......................... SUCCESS [ 14.947 s]
[INFO] Baleen Consumers ................................... SUCCESS [ 21.714 s]
[INFO] Baleen History ..................................... SUCCESS [  4.890 s]
[INFO] Baleen Runner ...................................... SUCCESS [ 12.928 s]
[INFO] Baleen Javadoc ..................................... SUCCESS [  0.849 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:25 min
[INFO] Finished at: 2016-04-12T19:26:36+04:00
[INFO] Final Memory: 127M/1136M
[INFO] ------------------------------------------------------------------------
```

**Comment by jbaker-dstl** [comment] 2016-04-13 08:04
2MB is about right for the documentation, so as you say it sounds as if it isn't building correctly. Despite the name, the Baleen Javadoc project doesn't actually build the Javadoc - it contains additional taglets to enhance the Javadoc (e.g. @baleen.config).

I believe you need to use the javadoc:aggregate-jar target in your Maven build.

**Comment by jbaker-dstl** [comment] 2016-06-09 09:33
Closing this issue as I'm not aware that this is still an issue. If it is an issue with the new version of Baleen (v2.2), please reopen/resubmit.

**Closed by jbaker-dstl** 2016-06-09 09:33 UTC
